CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    name  VARCHAR(250) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2000) NOT NULL,
    category_id        BIGINT NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id       BIGINT NOT NULL,
    lat                REAL,
    lon                REAL,
    paid               BOOLEAN NOT NULL,
    participant_limit  INTEGER NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN NOT NULL,
    state              VARCHAR(20) NOT NULL,
    title              VARCHAR(120) NOT NULL,

    CONSTRAINT fk_event_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id),

    CONSTRAINT fk_event_initiator
        FOREIGN KEY (initiator_id)
            REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id     BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status       VARCHAR(20) NOT NULL,

    CONSTRAINT fk_request_event
        FOREIGN KEY (event_id)
            REFERENCES events (id),

    CONSTRAINT fk_request_requester
        FOREIGN KEY (requester_id)
            REFERENCES users (id),

    CONSTRAINT uq_request
        UNIQUE (requester_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_events_category
    ON events (category_id);

CREATE INDEX IF NOT EXISTS idx_events_initiator
    ON events (initiator_id);

CREATE INDEX IF NOT EXISTS idx_events_state
    ON events (state);

CREATE INDEX IF NOT EXISTS idx_events_event_date
    ON events (event_date);

CREATE INDEX IF NOT EXISTS idx_requests_event
    ON requests (event_id);

CREATE INDEX IF NOT EXISTS idx_requests_requester
    ON requests (requester_id);

CREATE INDEX IF NOT EXISTS idx_requests_event_status
    ON requests (event_id, status);